-- Run once to create core tables including visitor attendance tracking.
-- Safe to re-run (uses IF NOT EXISTS).

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS accounts
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    orgname character varying(50) COLLATE pg_catalog."default",
    contact character varying(150) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    phone character varying(25) COLLATE pg_catalog."default",
    ein character varying(10) COLLATE pg_catalog."default",
    agree boolean,
    freeaccount boolean,
    accountkey uuid NOT NULL DEFAULT gen_random_uuid(),
    CONSTRAINT accounts_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_accountkey_key UNIQUE (accountkey)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS accounts
    ADD COLUMN IF NOT EXISTS accountkey uuid;

ALTER TABLE IF EXISTS accounts
    ALTER COLUMN accountkey SET DEFAULT gen_random_uuid();

UPDATE accounts
SET accountkey = gen_random_uuid()
WHERE accountkey IS NULL;

ALTER TABLE IF EXISTS accounts
    ALTER COLUMN accountkey SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'accounts_accountkey_key'
          AND conrelid = 'accounts'::regclass
    ) THEN
        ALTER TABLE accounts
            ADD CONSTRAINT accounts_accountkey_key UNIQUE (accountkey);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS connect_cards
(
    id serial NOT NULL,
    ministry_id uuid,
    visitor_key text COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(50) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT connect_cards_pkey PRIMARY KEY (id),
    CONSTRAINT connect_cards_ministry_id_fkey FOREIGN KEY (ministry_id)
        REFERENCES accounts (accountkey) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS connect_cards
    ADD COLUMN IF NOT EXISTS visitor_key text COLLATE pg_catalog."default";

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'connect_cards_ministry_id_fkey'
          AND conrelid = 'connect_cards'::regclass
    ) THEN
        ALTER TABLE connect_cards
            ADD CONSTRAINT connect_cards_ministry_id_fkey FOREIGN KEY (ministry_id)
                REFERENCES accounts (accountkey) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE NO ACTION;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_connect_cards_visitor_key
    ON connect_cards (visitor_key)
    WHERE visitor_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS attendance
(
    id bigserial NOT NULL,
    connect_card_id integer NOT NULL,
    ministry_id uuid,
    week_start date NOT NULL,
    scanned_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT attendance_pkey PRIMARY KEY (id),
    CONSTRAINT attendance_connect_card_id_fkey FOREIGN KEY (connect_card_id)
        REFERENCES connect_cards (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT attendance_ministry_id_fkey FOREIGN KEY (ministry_id)
        REFERENCES accounts (accountkey) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT attendance_connect_card_week_key UNIQUE (connect_card_id, week_start)
)

TABLESPACE pg_default;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'attendance_connect_card_week_key'
          AND conrelid = 'attendance'::regclass
    ) THEN
        ALTER TABLE attendance
            ADD CONSTRAINT attendance_connect_card_week_key UNIQUE (connect_card_id, week_start);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'attendance_connect_card_id_fkey'
          AND conrelid = 'attendance'::regclass
    ) THEN
        ALTER TABLE attendance
            ADD CONSTRAINT attendance_connect_card_id_fkey FOREIGN KEY (connect_card_id)
                REFERENCES connect_cards (id) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'attendance_ministry_id_fkey'
          AND conrelid = 'attendance'::regclass
    ) THEN
        ALTER TABLE attendance
            ADD CONSTRAINT attendance_ministry_id_fkey FOREIGN KEY (ministry_id)
                REFERENCES accounts (accountkey) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE NO ACTION;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
)

TABLESPACE pg_default;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'users_email_key'
          AND conrelid = 'users'::regclass
    ) THEN
        ALTER TABLE users
            ADD CONSTRAINT users_email_key UNIQUE (email);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS refresh_tokens
(
    id serial NOT NULL,
    user_id integer,
    token text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'refresh_tokens_user_id_fkey'
          AND conrelid = 'refresh_tokens'::regclass
    ) THEN
        ALTER TABLE refresh_tokens
            ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id)
                REFERENCES users (id) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE NO ACTION;
    END IF;
END $$;
    
CREATE INDEX IF NOT EXISTS idx_attendance_connect_card  ON attendance (connect_card_id);
CREATE INDEX IF NOT EXISTS idx_attendance_week          ON attendance (week_start);
CREATE INDEX IF NOT EXISTS idx_attendance_ministry      ON attendance (ministry_id);
